### ISSUE TITLE
You may want to look into using MailKit

### ISSUE THREAD

**Issue by jstedfast** [jan-schubert/MailMessaging#11]
Instead of implementing your own IMAP client which is a TON of work, you might be better off using [MailKit](https://github.com/jstedfast/MailKit) instead which is a very complete & robust IMAP client implementation.

**Comment by xp-development** [comment]
I know MailKit, but I want to create my own project to get knowledge about IMAP and cross platform development. I develop software with TDD since 9 years and now I am interested in cross-platform development with tests. So I want to write tests (unit tests, integration tests and automated UI tests) in one project and execute these tests for all technologies.

**Comment by jstedfast** [comment]
Okay, that's cool. Good luck, I think you'll find the IMAP protocol (especially some of the extensions) to be really cool.
